// Code generated by gen/gen_scan_float_rounded.go; DO NOT EDIT.
package scanner

import (
	"context"
	"io"
)

const vectorFloat32Size = 4 * 8

func scanFloat32Rounded(ctx context.Context, reader io.Reader, bufSize int, min float32, max float32, collector Collector) {
	var (
		chunk  = make([]byte, bufSize)
		offset = 0
	)

	for {
		if ctx.Err() != nil {
			return
		}

		n, err := io.ReadFull(reader, chunk)
		if n < 4 {
			break
		}

		// 保证处理的长度始终是对齐到 4 的
		processable := (n / 4) * 4

		scanFloat32Vectorized(chunk[:processable], min, max, offset, collector)
		offset += n

		if err != nil {
			// io.ErrUnexpectedEOF
			break
		}
	}
}
