// Code generated by gen/gen_scan_float_rounded.go; DO NOT EDIT.
package scanner

import (
	"context"
	"io"
)

const vectorFloat64Size = 8 * 8

func scanFloat64Rounded(ctx context.Context, reader io.Reader, bufSize int, min float64, max float64, collector Collector) {
	var (
		chunk  = make([]byte, bufSize)
		offset = 0
	)

	for {
		if ctx.Err() != nil {
			return
		}

		n, err := io.ReadFull(reader, chunk)
		if n < 8 {
			break
		}

		// 保证处理的长度始终是对齐到 8 的
		processable := (n / 8) * 8

		scanFloat64Vectorized(chunk[:processable], min, max, offset, collector)
		offset += n

		if err != nil {
			// io.ErrUnexpectedEOF
			break
		}
	}
}
