// Code generated by gen.go; DO NOT EDIT.
package scanner

import "unsafe"

func (s *Scanner) scanFloat32Unrolled(data []byte, min, max float32, offset int, results []int) []int {
	n := len(data)
	if n < 4 {
		return results
	}
	basePtr := uintptr(unsafe.Pointer(&data[0]))
	i := 0

	for ; i <= n-32; i += 32 {
		v0 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+0)))
		v1 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+4)))
		v2 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+8)))
		v3 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+12)))
		v4 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+16)))
		v5 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+20)))
		v6 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+24)))
		v7 := *(*float32)(unsafe.Pointer(basePtr + uintptr(i+28)))
		if v0 >= min && v0 < max {
			results = append(results, offset+i+0)
		}
		if v1 >= min && v1 < max {
			results = append(results, offset+i+4)
		}
		if v2 >= min && v2 < max {
			results = append(results, offset+i+8)
		}
		if v3 >= min && v3 < max {
			results = append(results, offset+i+12)
		}
		if v4 >= min && v4 < max {
			results = append(results, offset+i+16)
		}
		if v5 >= min && v5 < max {
			results = append(results, offset+i+20)
		}
		if v6 >= min && v6 < max {
			results = append(results, offset+i+24)
		}
		if v7 >= min && v7 < max {
			results = append(results, offset+i+28)
		}
	}

	for ; i <= n-4; i += 4 {
		val := *(*float32)(unsafe.Pointer(basePtr + uintptr(i)))
		if val >= min && val < max {
			results = append(results, offset+i)
		}
	}
	return results
}
