// Code generated by gen/gen_scan_float_vectorized.go; DO NOT EDIT.
package scanner

import "unsafe"

func scanFloat64Vectorized(data []byte, min, max float64, offset int, collector CollectorFunc) {
	n := len(data)
	if n < 8 {
		return
	}
	basePtr := uintptr(unsafe.Pointer(&data[0]))
	i := 0

	for ; i <= n-64; i += 64 {
		v0 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+0)))
		v1 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+8)))
		v2 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+16)))
		v3 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+24)))
		v4 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+32)))
		v5 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+40)))
		v6 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+48)))
		v7 := *(*float64)(unsafe.Pointer(basePtr + uintptr(i+56)))
		if v0 >= min && v0 < max {
			collector(offset + i + 0)
		}
		if v1 >= min && v1 < max {
			collector(offset + i + 8)
		}
		if v2 >= min && v2 < max {
			collector(offset + i + 16)
		}
		if v3 >= min && v3 < max {
			collector(offset + i + 24)
		}
		if v4 >= min && v4 < max {
			collector(offset + i + 32)
		}
		if v5 >= min && v5 < max {
			collector(offset + i + 40)
		}
		if v6 >= min && v6 < max {
			collector(offset + i + 48)
		}
		if v7 >= min && v7 < max {
			collector(offset + i + 56)
		}
	}

	for ; i <= n-8; i += 8 {
		val := *(*float64)(unsafe.Pointer(basePtr + uintptr(i)))
		if val >= min && val < max {
			collector(offset + i)
		}
	}
	return
}
